# Generated by Django 4.1 on 2022-08-23 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UsersList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, unique=True)),
                ('email', models.CharField(max_length=32, unique=True)),
                ('number_of_problems', models.IntegerField(default=0)),
                ('rating', models.IntegerField(default=1400)),
                ('account_image', models.ImageField(default='images/icon.jpg', upload_to='')),
                ('password', models.CharField(blank=True, max_length=32)),
                ('ez_problems', models.IntegerField(default=0)),
                ('medium_problems', models.IntegerField(default=0)),
                ('hard_problems', models.IntegerField(default=0)),
            ],
        ),
    ]
