# Generated by Django 4.1 on 2022-08-23 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userslist',
            options={'verbose_name': 'User'},
        ),
        migrations.AlterField(
            model_name='userslist',
            name='account_image',
            field=models.ImageField(default='icons', upload_to='images/icons'),
        ),
    ]
