# Generated by Django 4.1 on 2022-08-24 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_userslist_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userslist',
            name='index',
            field=models.IntegerField(default=0),
        ),
    ]
