# Generated by Django 4.1 on 2022-08-24 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_userslist_index'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weekly_contest', models.IntegerField(default=308)),
                ('biweekly_contest', models.IntegerField(default=86)),
                ('biweekly_date', models.DateTimeField(default='03.09.2022')),
            ],
        ),
    ]
