# Generated by Django 4.1 on 2022-08-24 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_contest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contest',
            name='biweekly_date',
            field=models.DateTimeField(),
        ),
    ]
