# Generated by Django 4.1 on 2022-09-06 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_contest_biweekly_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='userslist',
            name='image_url',
            field=models.URLField(default=2),
            preserve_default=False,
        ),
    ]
