# Generated by Django 4.1 on 2022-09-09 20:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_userslist_image_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userslist',
            name='account_image',
        ),
        migrations.RemoveField(
            model_name='userslist',
            name='password',
        ),
    ]
