# Generated by Django 4.1 on 2022-09-09 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_remove_userslist_account_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userslist',
            name='contest_num',
            field=models.IntegerField(default=0),
        ),
    ]
